'use client';
import { GamePhase, Player } from '@/lib/catan/types';
import { canAfford, BUILDING_COSTS } from '@/lib/catan/engine';
import { Dices, Home, Castle, Route, Layers, ArrowLeftRight, ArrowRight, X } from 'lucide-react';
interface Props {phase:GamePhase;player:Player;isMyTurn:boolean;rolling:boolean;buildMode:'road'|'settlement'|'city'|null;onSetBuildMode:(m:'road'|'settlement'|'city'|null)=>void;onRollDice:()=>void;onBuyDevCard:()=>void;onOpenTradeModal:()=>void;onOpenDevCardModal:()=>void;onEndTurn:()=>void;freeRoadsRemaining:number;}
export function ActionBar(p:Props) {
 const actions=p.phase==='TURN_ACTIONS'&&p.isMyTurn&&!p.rolling;
 const setup=p.phase.startsWith('SETUP');
 const costs={road:'1 wood · 1 brick',settlement:'1 wood · 1 brick · 1 wheat · 1 sheep',city:'2 wheat · 3 ore'};
 return <div className="action-bar"><div className="action-builds">{(['road','settlement','city'] as const).map(type=>{const Icon={road:Route,settlement:Home,city:Castle}[type];const supply={road:p.player.roadsLeft,settlement:p.player.settlementsLeft,city:p.player.citiesLeft}[type];const affordable=type==='road'&&p.freeRoadsRemaining>0||canAfford(p.player,BUILDING_COSTS[type]);return <button key={type} className={`build-button ${p.buildMode===type?'build-selected':''}`} disabled={!actions||!affordable||supply<=0} title={`${costs[type]}${!affordable?' — More resources needed':''}`} onClick={()=>p.onSetBuildMode(p.buildMode===type?null:type)}><Icon size={19}/><span>{type}<small>{type==='road'&&p.freeRoadsRemaining?`${p.freeRoadsRemaining} free`:`${supply} left`}</small></span></button>})}<button className="build-button" disabled={!actions||!canAfford(p.player,BUILDING_COSTS.dev_card)} onClick={p.onBuyDevCard} title="Development card: 1 wheat, 1 sheep, 1 ore"><Layers size={19}/><span>Develop<small>Buy a card</small></span></button></div>
 <div className="action-secondary"><button className="text-button" disabled={p.rolling} onClick={p.onOpenDevCardModal}><Layers size={15}/>My cards</button><button className="text-button" onClick={p.onOpenTradeModal} disabled={setup||p.rolling}><ArrowLeftRight size={15}/>Trade</button>{p.buildMode&&<button className="text-button" onClick={()=>p.onSetBuildMode(null)}><X size={14}/>Cancel</button>}</div>
 <div className="turn-action">{p.phase==='TURN_ROLL'&&p.isMyTurn?<button className="button button-primary" disabled={p.rolling} onClick={p.onRollDice}><Dices size={18}/>{p.rolling?'Rolling…':'Roll dice'}</button>:actions?<button className="button button-primary" onClick={()=>{p.onSetBuildMode(null);p.onEndTurn();}}>End turn<ArrowRight size={18}/></button>:<span className="turn-waiting">{p.rolling?'Rolling the dice…':setup?'Make yourself at home':p.isMyTurn?'Follow the island prompt':'Other settlers are playing'}</span>}</div></div>;
}
